included:
  - BudTransactions
excluded:
  - Pods
line_length: 360
identifier_name:
  min_length: # only min_length
    error: 2 # only error
  excluded:
    - id
    - URL
    - GlobalAPIKey
type_body_length:
  warning: 300
  error: 400
file_length:
  warning: 500
  error: 1000
disabled_rules:
    - large_tuple
reporter: "xcode"
